name: invoiceninja
version: '5.0.76'
summary: Online Invoicing
description: Create invoices, accept payments, track expenses & time-tasks
confinement: strict
base: core18
grade: stable

apps:
  invoiceninja:
    command: invoiceninja
    extensions: [flutter-stable]
    plugs:
      - network

parts:
  invoiceninja:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart